### ISSUE TITLE
'total'

### ISSUE THREAD

**Issue by debuos512** [bio-ontology-research-group/pmcanalysis#2]
hello, I am seeking a bit of advice about the 'total' number passed to the NPMI calculation in the FindDiseasePhenotypes.groovy script; in particular, how I can configure the parameter for another dataset. I suppose this is meant to be the total number of abstracts in the dataset? I see that it's hard-coded to 20000000 - is this correct?

**Comment by leechuck** [comment]
"total" is used in the computation of p(x) and the joint probability p(x,y). So this is either the number of abstracts or the number of abstracts in which we have found *any* match. The actual value does not matter too much as long as it's always larger than any number of occurrences (so that p is not >1).
